In [1]:
import pandas as pd
import numpy as np

from dataload import load_data

In [2]:
wdbc_x, wdbc_y = load_data("WDBC", split=False)
yeast_x, yeast_y = load_data("yeast", split=False)

In [3]:
wdbc_x.shape

(569, 30)

In [4]:
np.bincount(wdbc_y)

array([212, 357])

In [5]:
yeast_x.shape

(1484, 8)

In [6]:
np.bincount(yeast_y)

array([463,   5,  35,  44,  51, 163, 244, 429,  20,  30])

In [17]:
data = pd.read_fwf('yeast.csv', header=None).dropna()

In [22]:
data.iloc[:,5].unique()

array([0.5, 1. ])